[fix] CI 프로세스 수정.

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -3,7 +3,7 @@ name: CD Workflow
 on:
   push:
     branches:
-      - feature_CICD # 임시
+      - feature_CICDV1 # 임시
 
 jobs:
   deploy:
@@ -25,7 +25,57 @@ jobs:
           distribution: 'adopt'
           java-version: '17'
 
-    # 추후 추가.
+      - name: Create aws-info file
+        run: |
+          mkdir -p src/main/resources/aws
+          echo "${{ secrets.RDS_INFO }}" > src/main/resources/aws/rds-info.yml
+          echo "${{ secrets.S3_INFO }}" > src/main/resources/aws/s3-info.yml
+
+      - name: Create JAR file
+        run: |
+          chmod +x gradlew
+          ./gradlew clean bootJar
+          mkdir -p build/libs
+          cp build/libs/*.jar apiProject.jar
+
+      - name: Backup jar on remote server
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            TIMESTAMP=$(date +'%Y%m%d%H%M%S')
+            if [ -f bin/apiProject.jar ]; then
+              cp -a bin/apiProject.jar backup/apiProject_$TIMESTAMP.jar
+              echo "complete backup jar to backup/apiProject_$TIMESTAMP.jar"
+            fi
+
+      - name: Copy jar to remote server
+        uses: appleboy/scp-action@v0.1.3
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          target: bin
+          source: apiProject.jar
+          overwrite: true
+
+      - name: Execute deploy script on remote server
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            if [ -f bin/deploy.sh ]; then
+              echo "deploy.sh found, executing scripts..."
+              bin/deploy.sh dev
+              bin/deploy.sh local
+            else
+              echo "deploy.sh not found in bin directory"
+              exit 1
+            fi
 
   health-check:
     runs-on: ubuntu-latest
@@ -81,7 +131,7 @@ jobs:
         run: |
           VERSION=${{ steps.extract_version.outputs.version }}
           DATETIME=${{ steps.get_datetime.outputs.datetime }}
-          NEW_TAG="(test)${VERSION}_${DATETIME}"
+          NEW_TAG="${VERSION}_${DATETIME}"
           echo "New tag is $NEW_TAG"
           git tag $NEW_TAG
           git push origin $NEW_TAG
