[fix] CI 프로세스/ PR에 테스트가 적용되도록 변경 #342

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -54,7 +54,7 @@ jobs:
       - name: Build JAR File
         run: |
           chmod +x gradlew
-          ./gradlew clean bootJar
+          ./gradlew clean build
           mkdir -p build/libs
           cp build/libs/*.jar apiProject.jar
 
@@ -62,6 +62,11 @@ jobs:
         run: |
           aws s3 cp apiProject.jar s3://${{ secrets.S3_BUCKETNAME }}/jars/apiProject.jar --region ap-northeast-2
 
+  run-dev:
+    runs-on: ubuntu-latest
+    needs: deploy
+    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
+    steps:
       - name: Deploy via SSH
         uses: appleboy/ssh-action@master
         with:
@@ -75,12 +80,6 @@ jobs:
               echo "Failed to download JAR from S3."
               exit 1
             fi
-
-  run-dev:
-    runs-on: ubuntu-latest
-    needs: deploy
-    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
-    steps:
       - name: Execute deploy script on remote server
         uses: appleboy/ssh-action@master
         with:
@@ -101,6 +100,19 @@ jobs:
     needs: deploy
     if: github.event_name == 'push' && github.ref == 'refs/heads/prd'
     steps:
+      - name: Deploy via SSH
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST_ILSANG }}
+          username: ${{ secrets.EC2_ILSANG_USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY_ILSANG }}
+          script: |
+            echo "Downloading latest JAR from S3..."
+            aws s3 cp s3://${{ secrets.S3_BUCKETNAME }}/jars/apiProject.jar bin/apiProject.jar --region ap-northeast-2
+            if [ $? -ne 0 ]; then
+              echo "Failed to download JAR from S3."
+              exit 1
+            fi
       - name: Execute deploy script on remote server
         uses: appleboy/ssh-action@master
         with:
